spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: casp001
    password: Cws*1447
    url: jdbc:mysql://115.23.247.2:3306/kyro?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
    
## MULTIPART (MultipartProperties)
# Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
server:
  port: 8004
  address: 0.0.0.0
  servlet:
    context-path: /kyro
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

multipart:
  max-file-size: 100MB
  max-request-size: 100MB
  
file:
  upload-dir: D:/DataStorage/Kyro/Uploads


# upload-dir: /home/teodoro/Documents/DEV/CHOWIS/Project/Docs/uploads

